// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: validation.proto

package validationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PathKind is a ProtoBuf representation of the PathKind type, enumerating the different possible
// path kinds (i.e. denoting what the constraint violation is referring to at the given path).
type PathKind int32

const (
	PathKind_VALUE PathKind = 0
	PathKind_KEY   PathKind = 1
)

// Enum value maps for PathKind.
var (
	PathKind_name = map[int32]string{
		0: "VALUE",
		1: "KEY",
	}
	PathKind_value = map[string]int32{
		"VALUE": 0,
		"KEY":   1,
	}
)

func (x PathKind) Enum() *PathKind {
	p := new(PathKind)
	*p = x
	return p
}

func (x PathKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathKind) Descriptor() protoreflect.EnumDescriptor {
	return file_validation_proto_enumTypes[0].Descriptor()
}

func (PathKind) Type() protoreflect.EnumType {
	return &file_validation_proto_enumTypes[0]
}

func (x PathKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathKind.Descriptor instead.
func (PathKind) EnumDescriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{0}
}

// ConstraintViolation is a ProtoBuf representation of the the ConstraintViolation type, intended to
// allow ConstraintViolations to be used with gRPC more easily.
type ConstraintViolation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	PathKind PathKind         `protobuf:"varint,2,opt,name=path_kind,json=pathKind,proto3,enum=seeruk.validation.PathKind" json:"path_kind,omitempty"`
	Message  string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details  *structpb.Struct `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *ConstraintViolation) Reset() {
	*x = ConstraintViolation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_validation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstraintViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintViolation) ProtoMessage() {}

func (x *ConstraintViolation) ProtoReflect() protoreflect.Message {
	mi := &file_validation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintViolation.ProtoReflect.Descriptor instead.
func (*ConstraintViolation) Descriptor() ([]byte, []int) {
	return file_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ConstraintViolation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConstraintViolation) GetPathKind() PathKind {
	if x != nil {
		return x.PathKind
	}
	return PathKind_VALUE
}

func (x *ConstraintViolation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConstraintViolation) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_validation_proto protoreflect.FileDescriptor

var file_validation_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x73, 0x65, 0x65, 0x72, 0x75, 0x6b, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x38, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x73, 0x65, 0x65, 0x72, 0x75, 0x6b, 0x2e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x08, 0x70, 0x61, 0x74, 0x68, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2a, 0x1e, 0x0a, 0x08, 0x50, 0x61, 0x74, 0x68, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x4b, 0x45, 0x59, 0x10, 0x01, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x65, 0x72, 0x75, 0x6b, 0x2f, 0x67, 0x6f, 0x2d, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x3b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_validation_proto_rawDescOnce sync.Once
	file_validation_proto_rawDescData = file_validation_proto_rawDesc
)

func file_validation_proto_rawDescGZIP() []byte {
	file_validation_proto_rawDescOnce.Do(func() {
		file_validation_proto_rawDescData = protoimpl.X.CompressGZIP(file_validation_proto_rawDescData)
	})
	return file_validation_proto_rawDescData
}

var file_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validation_proto_goTypes = []interface{}{
	(PathKind)(0),               // 0: seeruk.validation.PathKind
	(*ConstraintViolation)(nil), // 1: seeruk.validation.ConstraintViolation
	(*structpb.Struct)(nil),     // 2: google.protobuf.Struct
}
var file_validation_proto_depIdxs = []int32{
	0, // 0: seeruk.validation.ConstraintViolation.path_kind:type_name -> seeruk.validation.PathKind
	2, // 1: seeruk.validation.ConstraintViolation.details:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_validation_proto_init() }
func file_validation_proto_init() {
	if File_validation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_validation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstraintViolation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_validation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validation_proto_goTypes,
		DependencyIndexes: file_validation_proto_depIdxs,
		EnumInfos:         file_validation_proto_enumTypes,
		MessageInfos:      file_validation_proto_msgTypes,
	}.Build()
	File_validation_proto = out.File
	file_validation_proto_rawDesc = nil
	file_validation_proto_goTypes = nil
	file_validation_proto_depIdxs = nil
}
